### ISSUE TITLE
Input assemblies for COBRA

### ISSUE THREAD

**Issue by asierFernandezP** [linxingchen/cobra#12]
Hi,

You mention that COBRA has so far only been tested on assembled contigs from metaSPAdes, IDBA_UD, and MEGAHIT. Would you recommend to use it on viral contigs that have been assembled using single cell mode (--sc) from SPAdes (used in our study for metaviromes)?
 
Thank you,
Asier

**Comment by linxingchen** [comment]
> Hi,
> 
> You mention that COBRA has so far only been tested on assembled contigs from metaSPAdes, IDBA_UD, and MEGAHIT. Would you recommend to use it on viral contigs that have been assembled using single cell mode (--sc) from SPAdes (used in our study for metaviromes)?
> 
> Thank you, Asier

Hi Asier,

I believe it is ok to use COBRA for your data, please select "metaspades" for the assembler option.

Let me know if you have other questions.

Best,
LINXING
