### ISSUE TITLE
ImportError: cannot import name 'GC' from 'Bio.SeqUtils'

### ISSUE THREAD

**Issue by funnell** [linxingchen/cobra#13]
On a new installation of cobra I run into this error:

```sh
❯ cobra-meta -h                                                                                  (cobra)
Traceback (most recent call last):
  File "/lila/home/funnellt/mambaforge/envs/cobra/bin/cobra-meta", line 6, in <module>
    from cobra import main
  File "/lila/home/funnellt/mambaforge/envs/cobra/lib/python3.8/site-packages/cobra.py", line 13, in <module>
    from Bio.SeqUtils import GC
ImportError: cannot import name 'GC' from 'Bio.SeqUtils' (/lila/home/funnellt/mambaforge/envs/cobra/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py)
```

I installed cobra using the instructions in the readme, which installed Biopython 1.82
```sh
❯ python                                                                                         (cobra)
Python 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:21:28)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> Bio.__version__
'1.82'
```

Looking through the Biopython NEWS.rst file, it looks like the GC module has been deprecated
https://github.com/biopython/biopython/blob/master/NEWS.rst

**Comment by linxingchen** [comment]
> On a new installation of cobra I run into this error:
> 
> ```shell
> ❯ cobra-meta -h                                                                                  (cobra)
> Traceback (most recent call last):
>   File "/lila/home/funnellt/mambaforge/envs/cobra/bin/cobra-meta", line 6, in <module>
>     from cobra import main
>   File "/lila/home/funnellt/mambaforge/envs/cobra/lib/python3.8/site-packages/cobra.py", line 13, in <module>
>     from Bio.SeqUtils import GC
> ImportError: cannot import name 'GC' from 'Bio.SeqUtils' (/lila/home/funnellt/mambaforge/envs/cobra/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py)
> ```
> 
> I installed cobra using the instructions in the readme, which installed Biopython 1.82
> 
> ```shell
> ❯ python                                                                                         (cobra)
> Python 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:21:28)
> [GCC 12.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import Bio
> >>> Bio.__version__
> '1.82'
> ```
> 
> Looking through the Biopython NEWS.rst file, it looks like the GC module has been deprecated https://github.com/biopython/biopython/blob/master/NEWS.rst

Hi, Tyler, Thank you for reporting this error and the information. Unfortunately, it is likely that they removed the GC function. Are you able to install an old version of BioPython, otherwise, it may take me several days to update the script including a new GC function? Please let me know. Thanks again. 

Best,
LINXING

**Comment by funnell** [comment]
Hello! Yes BioPython 1.81 works fine.

**Comment by linxingchen** [comment]
> Hello! Yes BioPython 1.81 works fine.

Hi Tyler, thanks for letting me know. I will add a note to the main page.

Best,
LINXING
