### ISSUE TITLE
multiple bam files

### ISSUE THREAD

**Issue by DOieGYuan** [linxingchen/cobra#14]
Hi Dr. Chen

Thank you for introducing this awesome tool!
What should I do if I have multiple bam files for the assembly built from multiple samples?
Thanks!

**Comment by linxingchen** [comment]
Hi, thank you for your interest in COBRA.

You could create only one bam file when mapping the reads, mapping tools could let you input several read sets from multiple samples.

Or, you could merge reads first then do the mapping to obtain only one bam file.

I hope this helps. Keep in mind that your contigs should be from a single assembly.

Best,
LinXing


LinXing Chen, Ph.D.
Associated Project Scientist,
The Banfield Lab,
University of California, Berkeley, USA 94706
Phone: (1)510-701-7864
Email: ***@***.***

2024年2月7日 -0800 PM11:16 DOieGYuan ***@***.***>，写道：

**Comment by DOieGYuan** [comment]
Thank you for your quick reply!
