### ISSUE TITLE
Using a co-assembyl

### ISSUE THREAD

**Issue by Balays** [linxingchen/cobra#18]
Hello, thank you for the great tool!
My question is that can the assembly come from several different but similar sources? I have gut microbiome samples from the same organisms but from different sampling times and indivduals and made a coassembly from them.
Thanks, Balazs

**Comment by linxingchen** [comment]
> Hello, thank you for the great tool! My question is that can the assembly come from several different but similar sources? I have gut microbiome samples from the same organisms but from different sampling times and indivduals and made a coassembly from them. Thanks, Balazs

Hi Balazs,

Yes, you can use co-assembly results for COBRA analyses, just need to ensure that you also use the combined paired-end reads to obtain the bam/sam file and also the contig depth/coverage file. Let me know if you have issues running it.

Best,
Linxing

**Comment by Balays** [comment]
Hi Linxing. 
Thank you for the quick answer. Altough I'm not quite ready yet with the assembly, as we got a long-read (ONT) sequeincg dataset ready, which I would like to incorporate so it will be a hybrid co-assembly.
Do you have any thoughts perhaps on how to do that the best? Have you experimented with a hybrid assembly?
Thank you. 
Bests, Balázs

**Comment by linxingchen** [comment]
Hi,

Unfortunately I do not have that experience. And COBRA does not work on long reads only short paired end reads FYI.

Best,
LinXing


LinXing Chen, Ph.D.
Associated Project Scientist,
The Banfield Lab,
University of California, Berkeley, USA 94706
Phone: (1)510-701-7864
Email: ***@***.***

2024年2月12日 -0800 AM3:54 Balázs Kakuk ***@***.***>，写道：
