### ISSUE TITLE
biopython issue / GC deprecation 

### ISSUE THREAD

**Issue by andriangajigan** [linxingchen/cobra#19]
Thank you for this amazing tool! 

I installed cobra using micromamba. biopython=1.81 is installed but the GC deprecation issue still ensued.

$ cobra-meta -f pelv_comb_mghit_fixed.fa -q bin.10.fa -c pelv.comb.cov.txt -m sorted_pelv_comb.bam -a megahit -mink 21 -maxk 141 -t 8

/Users/andriangajigan/mambaforge/envs/cobra/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py:144: BiopythonDeprecationWarning: GC is deprecated; please use gc_fraction instead.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/andriangajigan/mambaforge/envs/cobra/bin/cobra-meta", line 10, in <module>
    sys.exit(main())
  File "/Users/andriangajigan/mambaforge/envs/cobra/lib/python3.8/site-packages/cobra.py", line 818, in main
    cov[line[0]] = round(float(line[1]), 3)
ValueError: could not convert string to float: 'contigLen

$ conda list
packages in environment at /Users/andriangajigan/mambaforge/envs/cobra:

Name                    Version                   Build  Channel
biopython                 1.81             py38hae2e43d_1    conda-forge
blast                     2.15.0          pl5321h91c44f7_1    bioconda
bzip2                     1.0.8                h10d778d_5    conda-forge
c-ares                    1.26.0               h10d778d_0    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
cobra-meta                1.2.2              pyhdfd78af_0    bioconda
curl                      8.5.0                h726d00d_0    conda-forge
entrez-direct             16.2                 h193322a_1    bioconda
gettext                   0.21.1               h8a4c099_0    conda-forge
krb5                      1.21.2               hb884880_0    conda-forge
libblas                   3.9.0           21_osx64_openblas    conda-forge
libcblas                  3.9.0           21_osx64_openblas    conda-forge
libcurl                   8.5.0                h726d00d_0    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.18                 hac1461d_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 h10d778d_2    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_2    conda-forge
libgfortran5              13.2.0               h2873a65_2    conda-forge
libiconv                  1.17                 hd75f5a5_2    conda-forge
libidn2                   2.3.7                h10d778d_0    conda-forge
liblapack                 3.9.0           21_osx64_openblas    conda-forge
libnghttp2                1.58.0               h64cf6d3_1    conda-forge
libopenblas               0.3.26          openmp_hfef2a42_0    conda-forge
libsqlite                 3.44.2               h92b6c6a_0    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               17.0.6               hb6ac08f_0    conda-forge
ncbi-vdb                  3.0.0           pl5321h9722bc1_0    bioconda
ncurses                   6.4                  h93d8f39_2    conda-forge
numpy                     1.24.4           py38h9a4a08f_0    conda-forge
openssl                   3.2.1                hd75f5a5_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
perl                      5.32.1          7_h10d778d_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h775f41a_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h775f41a_0    conda-forge
perl-encode               3.19            pl5321hb7f2c08_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.201           pl5321h7133b54_2    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321hcd10b59_5    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda

Thanks in advance!

**Comment by linxingchen** [comment]
Hi, 

Thank you for your interest in COBRA. My bad that you should use Biopython 1.79 or older version to avoid this error. I will release a new version soon to fix this problem. 

Please let me know if this works or not.

Best,
LINXING

**Comment by andriangajigan** [comment]
HI again,

I tried v1.79 and 1.74. This time different error. 

Traceback (most recent call last):
  File "/Users/andriangajigan/mambaforge/envs/cobra/bin/cobra-meta", line 10, in <module>
    sys.exit(main())
  File "/Users/andriangajigan/mambaforge/envs/cobra/lib/python3.8/site-packages/cobra.py", line 818, in main
    cov[line[0]] = round(float(line[1]), 3)
ValueError: could not convert string to float: 'contigLen'

**Comment by linxingchen** [comment]
Hi, it looks like your contig depth/coverage file contains header that the second column is not a number but "contigLen", please check it and remove the first line.

**Comment by linxingchen** [comment]
Do you mean that the output file of `coverage.transfer.py` still has the header line with "contigLen"? If yes, could you please show me your original depth file, probably just the first 5 lines? Thank you.

**Comment by andriangajigan** [comment]
It worked now. I meant I used the coverage.transfer.py to convert the jgi_summarize_bam_contig_depths coverage file as suggested in the main instruction: python coverage.transfer.py -i original.coverage.txt -o coverage.txt

**Comment by linxingchen** [comment]
Did you mean when you used the `coverage.transfer.py` script, then everything is fine right?
