### ISSUE TITLE
Randomly not getting full output

### ISSUE THREAD

**Issue by pck00** [linxingchen/cobra#20]
Hello, 

I have noticed that with some COBRA runs, COBRA randomly aborts after "Saving joining summary of "Extended_circular" and "Extended_partial" query contigs". The log files just end there, and the fasta files in question are missing. Everything else is there. Instead of the missing self circular files, I get what appears to be blast databases (blastdb_1 and blastdb_2) as output.

Rerunning the metagenomic analysis on the exact same original fastq files, starting with megahit assembly, it randomly works fine. All output files up until running coverage_transfer.py are identical (with slight contig naming differences because of megahit), I can not tell a difference in runs up until COBRA comes in the picture, and even log and debug files are identical up until the "Saving joining summary of "Extended_circular" and "Extended_partial" query contigs"

Very strange bug, and not sure how to figure out what's wrong since it appears random. Happy to provide successful/unsuccessful run data, just not sure what would help and don't want to dump it all here.

**Comment by linxingchen** [comment]
Hi, 

Thank you for reporting this issue.

I think i have heard about it from others as well, but have not got time to fix it.

Am I correct that, for the same sample but with different assemblers, one did not finish but the other (MEGAHIT) finished well?

If yes, could you please share me several files, (1) COBRA_end_joining_pairs.txt (2) COBRA_potential_joining_paths.txt and (3) debug file? Thank you.

Best,
LINXING

**Comment by pck00** [comment]
I'm always using megahit. 
[working debug.txt](https://github.com/linxingchen/cobra/files/14312711/working.debug.txt)
[working COBRA_end_joining_pairs.txt](https://github.com/linxingchen/cobra/files/14312712/working.COBRA_end_joining_pairs.txt)
[working COBRA_potential_joining_paths.txt](https://github.com/linxingchen/cobra/files/14312713/working.COBRA_potential_joining_paths.txt)

**Comment by pck00** [comment]
Not working ones:
[debug.txt](https://github.com/linxingchen/cobr
[COBRA_end_joining_pairs.txt](https://github.com/linxingchen/cobra/files/14312724/COBRA_end_joining_pairs.txt)
[COBRA_potential_joining_paths.txt](https://github.com/linxingchen/cobra/files/14312725/COBRA_potential_joining_paths.txt)
a/files/14312722/debug.txt)

**Comment by linxingchen** [comment]
thanks for sharing the files. for the ones that did not finish, what errors did you get?

**Comment by linxingchen** [comment]
I have fixed the bug raised in Issue #21 . Enclosed is the modified version, could you please see if it works? Thank you.
[cobra_test.py.zip](https://github.com/linxingchen/cobra/files/14316874/cobra_test.py.zip)

**Comment by pck00** [comment]
All is solved, it works now, thank you!
