### ISSUE TITLE
KeyError for extended_circular_fasta.write(header2joined_seq[contig2extended_status[contig]] + '\n')                                                                                   

### ISSUE THREAD

**Issue by Chrisjrt** [linxingchen/cobra#21]
Hey LinXing, 

First, thanks for developing this super useful tool! I've so far ran it on a couple hundred virome samples and it's working great! I have stumbled across an issue with 2 samples though that I was wondering if you could help me with. For each of the 2 metagenomes I get this error (but obviously a different key value differing the messages):

```
Traceback (most recent call last):                                                                                                                                            
  File ".snakemake/conda/e7dfc9b82d378646d96b58efd8350561_/bin/cobra-meta", line 12, in <module>                  
    sys.exit(main())                                                                                                                                                          
  File ".snakemake/conda/e7dfc9b82d378646d96b58efd8350561_/lib/python3.10/site-packages/cobra.py", line 1598, in m
ain                                                                                                                                                                           
    extended_circular_fasta.write(header2joined_seq[contig2extended_status[contig]] + '\n')                                                                                   
KeyError: 'NODE_404_length_6556_cov_28.183972'
```

I checked for these keys in the whole contig set (the scaffold.fasta output by metaspades); query file (all scaffolds >2.5kbp from the metaspades scaffolds.fasta); and the coverage file. It is present in each of those files with no additional characters. So, I'm a bit confused with what the source of the problem could be (especially since the couple of hundred other samples i've processed worked fine!). Any help you could give would be much appreciated!

The the log file looks like this:

```
1. INPUT INFORMATION
# Assembler: metaSPAdes
# Min-kmer: 21
# Max-kmer: 55
# Overlap length: 55 bp
# Read mapping max mismatches for contig linkage: 2
# Query contigs: /data/san/data0/users/chris/data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds_over_2.5kb.fasta
# Whole contig set: /data/san/data0/users/chris/data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds.fasta
# Mapping file: /data/san/data0/users/chris/data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds_sorted.bam
# Coverage file: /data/san/data0/users/chris/data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds.coverage.formatted.txt
# Output folder: /data/san/data0/users/chris/data/processed/assemblies/spades_CTRLM08LongB03Faeces/cobra

2. PROCESSING STEPS
[01/23] [2024/02/16 00:22:53] Reading contigs and getting the contig end sequences. A total of 255643 contigs were imported.
[02/23] [2024/02/16 00:22:58] Getting shared contig ends.
[03/23] [2024/02/16 00:23:00] Writing contig end joining pairs.
[04/23] [2024/02/16 00:23:00] Getting contig coverage information.
[05/23] [2024/02/16 00:23:00] Getting query contig list. A total of 2314 query contigs were imported.
[06/23] [2024/02/16 00:23:00] Getting contig linkage based on sam/bam. Be patient, this may take long.
[07/23] [2024/02/16 00:23:38] Parsing the linkage information.
[08/23] [2024/02/16 00:23:43] Detecting self_circular contigs.                                                                                                                     "zEQ$" 23:44 15-Feb-24
[09/23] [2024/02/16 00:23:43] Detecting joins of contigs. 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100% finished.
[10/23] [2024/02/16 00:23:46] Saving potential joining paths.
[11/23] [2024/02/16 00:23:46] Checking for invalid joining: sharing queries.
[12/23] [2024/02/16 00:23:47] Getting initial joining status of each query contig.
[13/23] [2024/02/16 00:23:47] Getting final joining status of each query contig.
[14/23] [2024/02/16 00:23:47] Getting the joining order of contigs.
[15/23] [2024/02/16 00:23:47] Getting retrieved contigs.
[16/23] [2024/02/16 00:23:47] Saving joined seqeuences.
[17/23] [2024/02/16 00:23:47] Checking for invalid joining using BLASTn: close strains.
[18/23] [2024/02/16 00:23:48] Saving unique sequences of "Extended_circular" and "Extended_partial" for joining checking.
```

**Comment by linxingchen** [comment]
Hi, 

Thank you for your interest in COBRA, I am glad it helps for your analyses. 

Regarding these two samples, could you please share these files with me , (1) COBRA_end_joining_pairs.txt (2) COBRA_potential_joining_paths.txt and (3) debug file? 

Thank you.

Best,
LINXING

**Comment by Chrisjrt** [comment]
Sure, here are those 3 files for sample 1 (key error in this case was 'NODE_67_length_39995_cov_222.169830')

[COBRA_end_joining_pairs.txt](https://github.com/linxingchen/cobra/files/14304106/COBRA_end_joining_pairs.txt)
[COBRA_potential_joining_paths.txt](https://github.com/linxingchen/cobra/files/14304109/COBRA_potential_joining_paths.txt)
[debug.txt](https://github.com/linxingchen/cobra/files/14304110/debug.txt)

**Comment by Chrisjrt** [comment]
And here they are for sample 2 (key error here was 'NODE_404_length_6556_cov_28.183972')

[COBRA_end_joining_pairs.txt](https://github.com/linxingchen/cobra/files/14304194/COBRA_end_joining_pairs.txt)
[COBRA_potential_joining_paths.txt](https://github.com/linxingchen/cobra/files/14304198/COBRA_potential_joining_paths.txt)
[debug.txt](https://github.com/linxingchen/cobra/files/14304200/debug.txt)

**Comment by linxingchen** [comment]
Thank you Chris. I will take a look ASAP and let you know what is the wrong.

**Comment by linxingchen** [comment]
> And here they are for sample 2 (key error here was 'NODE_404_length_6556_cov_28.183972')
> 
> [COBRA_end_joining_pairs.txt](https://github.com/linxingchen/cobra/files/14304194/COBRA_end_joining_pairs.txt) [COBRA_potential_joining_paths.txt](https://github.com/linxingchen/cobra/files/14304198/COBRA_potential_joining_paths.txt) [debug.txt](https://github.com/linxingchen/cobra/files/14304200/debug.txt)

Hi Chirs, unfortunately I was not able to locate the bug with the files you provided. Do you mind sharing all the input files of this sample, so I can run COBRA on my end and try to debug it? No worries if you do not want to do so.

LINXING

**Comment by Chrisjrt** [comment]
Yeah sure no problem, I'll send them onto the gmail address you provided in a different issue post. Thanks again for taking a look at the issue!

In case you need it here is the command i'm running for sample 1 (so same for sample 2 except paths to files)

```
cobra-meta -f data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds.fasta -q data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds_over_2.5kb.fasta -
c data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds.coverage.formatted.txt -m data/processed/assemblies/spades_CTRLM08LongB03Faeces/scaffolds_sorted.bam -a metaspa
des -mink 21 -maxk 55 -t 10 -o data/processed/assemblies/spades_CTRLM08LongB03Faeces/cobra/ 
```

**Comment by Chrisjrt** [comment]
Sent :)

**Comment by linxingchen** [comment]
> Sent :)

Hi Chris, unfortunately I do not see the email. Could you please confirm?

**Comment by Chrisjrt** [comment]
I sent it to the linkingchanATgmailDOTcom address you posted in another email. Is this not the correct email?

**Comment by Chrisjrt** [comment]
i sent it via wetransfer so may be in your spam if that is the correct email

**Comment by linxingchen** [comment]
Hi Chris, I think I was able to fix the bug. Could you please try this version and let me know if it works for you or not? Thank you.
[cobra_test.py.zip](https://github.com/linxingchen/cobra/files/14316870/cobra_test.py.zip)

**Comment by Chrisjrt** [comment]
Hey LinXing, 

Yeah, that seems to have fixed the issue! Both sample now run to completion 😄

**Comment by linxingchen** [comment]
That's good to know. Thank you for help. I will release a new version asap.

**Comment by Chrisjrt** [comment]
No problem and thank you for the rapid fix!
