### ISSUE TITLE
Application of COBRA to stool whole metagenome datasets

### ISSUE THREAD

**Issue by jylee3247** [linxingchen/cobra#22]
Hello,

First of all, thank you for developing this great tool!

I recently read your [published paper](https://www.nature.com/articles/s41564-023-01598-2#Sec26).
I would like to ask about the current recommendations or precautions for applying COBRA to stool whole metagenome datasets.

From what I understand based on the version uploaded to [bioRxiv](https://www.biorxiv.org/content/10.1101/2023.05.30.542503v2.full), there was exploration into its use for microbial genomes. However, it seems this part was excluded from the published version during the revision process (I saw it in peer review comments).

1. Are there any current recommendations for applying COBRA to whole metagenome datasets?
Is performing contig extension with COBRA before binning currently the best practice, as mentioned in the revision comments?

4. Is it possible to apply COBRA like bewlow workflow (mutiple binning tools followed by binning refinement)
> 1) contig extension with COBRA
> 2) binning using multiple binner (such as MetaBAT, MaxBin, CONCOCT, Binsanity etc.)
> 3) binning refinement (e.g., DAS tool) process.

I would assume performing this process individually for each sample wouldn't raise any problems, but I wonder if you have any experiences or concerns regarding this workflow.

Thank you for taking the time to read my questions.
If there are any misunderstandings on my part, I would appreciate your kind correction.

Regards,

**Comment by linxingchen** [comment]
Hi,

Thank you for your interest in COBRA. 

You are right that we evaluated the use of COBRA on microbial genomes and metagenomes, as you can see from the Reviewers' comments that Reviewer 2 strongly discourage this. However, our own test suggested it is safe and reliable, it sometimes is able to join a 16S rRNA contig/scaffold that could usually been missed in binning. 

Your workflow looks good, but should add one more step, that's doing another run of reads mapping and coverage calculation after contig extension using the new fasta file that COBRA provides.

Please let me know if you have any other concerns. Always glad to talk more.

Best,
LINXING

**Comment by jylee3247** [comment]
Thank you for your kind and detailed guidance.

I'm going to incorporate your suggested step and apply it to the whole metagenome dataset.

If there are further questions, I'll ask you.

Thank you very much!

Regards,
