### ISSUE TITLE
About the usage of COBRA

### ISSUE THREAD

**Issue by MengzhiJ** [linxingchen/cobra#32]
Dear Linxing,

Thank you for providing an excellent tool for viral metagenomic studies. I have a question about the usage of COBRA:

I want to improve the genome quality of viruses recovered from multi-sample coassembled metagenomes (such as A1, A2, A3). In this case, I merged the mapping files of each metagenome (i.e., A1.bam A2.bam A3.bam > merge.bam) as the bam input and calculate the coverage file using jgi_summarize_bam_contig_depths (the first column was contig name, the second to fourth columns were the coverage of A1, A2, A3) as the coverage input. I'm not sure if my inputs to COBRA were correct. 

Regards,
Mengzhi

**Comment by linxingchen** [comment]
Hi Mengzhi,

Thank you for your interest in COBRA.

You should combine your reads of your samples for mapping to get the bam file and also the coverage. COBRA only accepts one coverage value for each contig or scaffold. I hope this helps and please let me know if you have any other question.

Best,
Linxing

**Comment by MengzhiJ** [comment]
Hi Linxing,

Thank you! I'm curious if this will affect the accuracy of COBRA. Specifically, I want to know if COBRA works better for viruses recovered from single-sample assembly compared to multi-sample assembly.

**Comment by linxingchen** [comment]
It is really difficult to say, totally up to the population variation rates of each virus. I prefer using COBRA on single-sample assembly though.
