### ISSUE TITLE
cobra-meta: error: unrecognized arguments: 2

### ISSUE THREAD

**Issue by Songq-20** [linxingchen/cobra#40]
Hi Dr. Chen,
I encountered this problem while testing COBRA：
My command:
```
cobra-meta -f MG_CE.fasta -q MG_CE_query_id.txt -o cobra-test-out -c coverage.txt -m MG_CE-cobra-fs.bam -a megahit -mink 21 -maxk 141 -mm 2
```
Error:
```
usage: cobra-meta [-h] -q QUERY -f FASTA -a {idba,megahit,metaspades} -mink MINK -maxk MAXK -m MAPPING -c COVERAGE [-lm LINKAGE_MISMATCH] [-o OUTPUT] [-t THREADS] [-v]
cobra-meta: error: unrecognized arguments: 2
```
And it can run after deleting `-mm 2`.
Or I may input `-lm 2` instand of `-mm 2`? If that's the case, you may need to modify the `How to run` section in the README.md.

Thanks!

**Comment by linxingchen** [comment]
Hi Songq-20,

Thank you for the error report. 

The READE.md file has now been modified. I'm pretty sure that it is a typo. 

Best,
LINXING
