### ISSUE TITLE
Multi-bam as an input

### ISSUE THREAD

**Issue by Andyargueasae** [linxingchen/cobra#48]
Hi, 
Just found that cobra doesn't accept multiple bam files as the input. So is cobra only applied to one sample at a time?

Cheers
Yuhao from university of Melbourne

**Comment by linxingchen** [comment]
Hi Yuhao,

Yes, you are right that COBRA could work on only one sample each time, because it is based on the DBG assembly. 

Best,
Linxing

**Comment by Andyargueasae** [comment]
Alright, thanks.
